# FS service definition for tenant-1.
apiVersion: v1
kind: Service
metadata:
  name: fs
spec:
  selector:
    app: fs
  ports:
    - port: 9091
      targetPort: 9091
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs
  labels:
    app: fs
spec:
  selector:
    matchLabels:
      app: fs
  template:
    metadata:
      labels:
        app: fs
    spec:
      containers:
        - name: api
          image: nicholasjackson/fake-service:v0.7.8
          ports:
            - containerPort: 9091
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:9091'
            - name: 'NAME'
              value: 'tenant-2'
            - name: 'MESSAGE'
              value: 'Response from tenant-2'

